### ISSUE TITLE
matrixcompare uses num_traits::Float without std

### ISSUE THREAD

**Issue by 0ncorhynchus** [Andlon/matrixcompare#3]
This is a bug report.

I tried to use `matrixcompare` as a dependency with a tiny sample `Cargo.toml` shown as the below:
```Cargo.toml
[package]
name = "tmp"
version = "0.1.0"
edition = "2018"

[dependencies]
matrixcompare = "0.1.3"
```
However, `cargo check` failed with the message like:
```console
$ cargo check
    Checking matrixcompare v0.1.3
error[E0432]: unresolved import `num_traits::Float`
 --> /home/kato/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixcompare-0.1.3/src/comparators.rs:5:18
  |
5 | use num_traits::{Float, Num};
  |                  ^^^^^
  |                  |
  |                  no `Float` in the root
  |                  help: a similar name exists in the module (notice the capitalization): `float`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `matrixcompare`.

To learn more, run the command again with --verbose.
```

This is caused by that `matrixcompare` uses `num_traits::Float` without the `std` feature of `num-traits`.
I found out from `Cargo.toml` of this crate that it is expected behavior to use `num-traits` without the `std` feature.
https://github.com/Andlon/matrixcompare/blob/8fa1ad31f61abbdd2b40530b2aa99badf14ef642/Cargo.toml#L13

On the other hand, `num-traits` doesn't export [`Float`](
https://github.com/rust-num/num-traits/blob/f6852e047c9dd673078b73400ed666b7d4e1684f/src/lib.rs#L33-L34) without `std` or `libm` features.

So, `matrixcompare` tries to use `num_traits::Float`, which is not exported.

By the way, `matrixcompare` is successfully built on the  CI now. This is due to the [bug](https://github.com/rust-lang/cargo/issues/7916) of `cargo`. 
`matrixcompare` uses `proptest` as a dev-dependency. (and it uses `num-traits` with the default features including `std`!)
This is the reason that `cargo` uses `num-traits` with the `std` feature when building `matrixcompare` as a root crate.
At the last, when I tried to build `matrixcompare` with the nightly version of `cargo`, building failed:
```console
$ cargo +nightly -Z features=dev_dep check
   Compiling autocfg v1.0.1
    Checking matrixcompare-core v0.1.0 (/home/kato/wrk/develop/matrixcompare/matrixcompare-core)
   Compiling num-traits v0.2.12
    Checking matrixcompare v0.1.3 (/home/kato/wrk/develop/matrixcompare)
error[E0432]: unresolved import `num_traits::Float`
 --> src/comparators.rs:5:18
  |
5 | use num_traits::{Float, Num};
  |                  ^^^^^
  |                  |
  |                  no `Float` in the root
  |                  help: a similar name exists in the module (notice the capitalization): `float`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `matrixcompare`.

To learn more, run the command again with --verbose.
```

**Comment by Andlon** [comment]
Hi @0ncorhynchus, thanks for figuring this out! I'm sorry I didn't get back to you sooner, I don't recall having being notified of this issue, so I unfortunately missed it. I will take a look at your PR now and publish an updated release shortly!

**Comment by Andlon** [comment]
In addition to merging your PR, I added the compilation of a "hello world" crate (basically your example) to the CI, to prevent future regressions. Thanks again for notifying me of the issue!

(For some reason, notifications were not enabled on this repo for me, which is why I did not notice your issue before now. In the future, I should hopefully receive notifications in a timely manner.)

**Comment by 0ncorhynchus** [comment]
Don't worry about it :smiley: 
I thank you for your good project!
